import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { test } from 'vitest';
import { runSize, BUDGET_MS, type SizeResult, type OpResult } from './harness';
import { burnMarkdown } from './burn';

/** node counts the user asked for; edges ≈ 1.5× (a CPG is edge-dense).
 *  `BENCH_MAX` caps the largest size (use 1000 for fast per-step regression runs). */
const MAX = Number(process.env.BENCH_MAX ?? Infinity);
const SIZES: Array<[nodes: number, edges: number]> = [
  [1, 0],
  [100, 150],
  [1_000, 1_500],
  [10_000, 15_000],
  [100_000, 150_000],
].filter(([n]) => n <= MAX);

const OPS = ['load', 'add', 'move-multiple', 'zoom', 'pan', 'collapse', 'expand', 'select+delete'];
/** `BENCH_OUT` lets a worktree run write its labeled result back into the main repo. */
const OUT = process.env.BENCH_OUT || resolve(process.cwd(), 'dx/bench/RESULTS.md');
const LABEL = process.env.BENCH_LABEL ? ` — ${process.env.BENCH_LABEL}` : '';

/** Per-op history of real (run, not projected) datapoints → power-law predict. */
type Point = { n: number; ms: number };
const history = new Map<string, Point[]>();

function predictFor(nextN: number) {
  return (op: string): number | null => {
    const pts = history.get(op);
    if (!pts || pts.length < 2) return null;
    const a = pts[pts.length - 2], b = pts[pts.length - 1];
    if (a.ms <= 0 || b.ms <= 0 || a.n === b.n) return b.ms;
    const exp = Math.log(b.ms / a.ms) / Math.log(b.n / a.n); // local power-law exponent
    return b.ms * Math.pow(nextN / b.n, exp);
  };
}

function record(size: SizeResult) {
  for (const o of size.ops) {
    if (Number.isFinite(o.ms)) {
      const pts = history.get(o.op) ?? history.set(o.op, []).get(o.op)!;
      pts.push({ n: size.nodes, ms: o.ms });
    }
  }
}

const cell = (o: OpResult | undefined): string => {
  if (!o) return '—';
  if (o.projected != null) return `_~${Math.round(o.projected).toLocaleString()}_ 🚫`;
  return `${o.ms < 1 ? o.ms.toFixed(2) : Math.round(o.ms).toLocaleString()}${o.over ? ' ⚠️' : ''}`;
};

function render(results: SizeResult[]): string {
  const header = `# Graph performance benchmark${LABEL}

> Generated by \`npm run bench\` / \`npm run bench:burn\` (\`tests/bench/\`). jsdom + memory IO, **real app boot**.
> Cell = wall-clock **ms** per op incl. redraw settle. \`⚠️\` = measured over ${(BUDGET_MS / 1000)}s budget.
> \`_~n_ 🚫\` = **not run** — projected (power-law from smaller sizes) to exceed budget; running it
> would hang jsdom (single-threaded, no interrupt). jsdom has no real layout/paint, so these
> isolate **JS + DOM-construction** cost — the algorithmic ceiling. Real GPU paint = Playwright pass.

Node | Edges | ${OPS.join(' | ')}
---|---|${OPS.map(() => '--:').join('|')}`;
  const rows = results.map(r =>
    `${r.nodes.toLocaleString()} | ${r.edges.toLocaleString()} | ${OPS.map(op => cell(r.ops.find(x => x.op === op))).join(' | ')}`);
  return `${header}
${rows.join('\n')}

## Burn — hot paths (model methods, ranked by total time)

_Run \`npm run bench:burn\` to populate. Counters wrap \`Graph\` methods flagged O(n)/allocating._

${burnMarkdown()}

_Updated: ${new Date().toISOString()}_
`;
}

test('graph perf bench', { timeout: 15 * 60_000 }, async () => {
  mkdirSync(dirname(OUT), { recursive: true });
  const results: SizeResult[] = [];
  for (const [nodes, edges] of SIZES) {
    const r = await runSize(nodes, edges, predictFor(nodes));
    record(r);
    results.push(r);
    writeFileSync(OUT, render(results)); // checkpoint after every size
  }
  // eslint-disable-next-line no-console
  console.log(`\nBench written → ${OUT}`);
});
