import type { Registry } from '../core';
import { registerCancellation } from './cancellation';
import { registerChoose } from './choose';
import { registerCollections } from './collections';
import { registerCommandModal } from './command-modal';
import { registerCommandForm } from './command-form';
import { registerCommandPicker } from './command-picker';
import { registerContainers } from './containers';
import { registerContextActions } from './context-actions';
import { registerDarkTheme } from './dark-theme';
import { registerDebug } from './debug';
import { registerDetail } from './detail';
import { registerDemo } from './demo';
import { registerDx } from './dx';
import { registerFoldable } from './foldable';
import { registerFocus } from './focus';
import { registerGraph } from './graph';
import { registerInput } from './input';
import { registerIo } from './io';
import { registerJump } from './jump';
import { registerLayout } from './layout';
import { registerLog } from './log';
import { registerMain } from './main';
import { registerModal } from './modal';
import { registerItemToolbar } from './item-toolbar';
import { registerNodeAutosize } from './node-autosize';
import { registerNodeVisuals } from './node-visuals';
import { registerRender } from './render';
import { registerRenderStage } from './render-stage';
import { registerScenario } from './scenario';
import { registerShare } from './share';
import { registerTextLayout } from './text-layout';
import { registerToolPanel } from './tool-panel';
import { registerVarflow } from './varflow';
import { registerViewPan } from './view-pan';
import { registerViewZoom } from './view-zoom';

export function registerSystems(system: Registry) {
  registerRender(system);
  registerDarkTheme(system);
  registerRenderStage(system);
  registerTextLayout(system);
  registerInput(system);
  registerIo(system);
  registerFoldable(system);
  registerCancellation(system);
  registerMain(system);
  registerToolPanel(system);
  registerLog(system);
  registerModal(system);
  registerCommandForm(system);
  registerCommandPicker(system);
  registerCommandModal(system);
  // Jump must register before `collections` so its `g` binding sits earlier in
  // the input router's enabled() iteration — combined with `stop: true` it then
  // shadows `graph.switch.next` instead of doubling up.
  registerJump(system);
  registerCollections(system);
  registerGraph(system);
  registerViewZoom(system);
  registerViewPan(system);
  registerFocus(system);
  registerLayout(system);
  registerContextActions(system);
  registerItemToolbar(system);
  registerNodeVisuals(system);
  registerNodeAutosize(system);
  registerContainers(system);
  registerChoose(system);
  registerDetail(system);
  registerDemo(system);
  registerDebug(system);
  registerScenario(system);
  registerShare(system);
  registerVarflow(system);
  registerDx(system);
}
